### PR TITLE
Add export to graphviz

### PR DESCRIPTION
**Pull request by apraga**
The functions requires a layout. Some advice is in the documentation. 

For readability, nodes only have the term name and spaces are replaced by newlines. With the fdp layout, it gives quite nice result but I'm open to discussing this.

Thanks,

### CODE REVIEW

**Comment by anergictcell** [comment]
I like the idea. It makes sense to provide graphviz output. I don't know that much about graphviz, but do you have to specify the layout in the code? I think you can leave it out and one can specify the layout when constructing the actual graphs with graphviz later, right?

**Comment by apraga** [comment]
A default layout is indeed set by graphviz if not specified, but I found it more user-friendly to be able to set it from rust. Ideally, we could set the argument to a default value, but it doesn’t seem doable in rust ?

**Comment by anergictcell** [comment]
Default values are not that easy to implement, you would need to define a new struct for the config or use an `Option`. I think that would be too overblown.
I made two minor edits and will merge the changes.

**Comment by apraga** [comment]
Thanks !

**Pull request merged**
